### ISSUE TITLE
Cannot instal with pip install dbt-ipy

### ISSUE THREAD

**Issue by MateTorok** [jmriego/dbt-ipy#2]
Hello,

This seems to be a really useful and great package however I get the following error when trying to install it. Is there any other way of installing besides $pip install dbt-ipy ?

    Using cached dbt_ipy-1.0.0-py3-none-any.whl (17 kB)
    Collecting dbt>=0.18
      Using cached dbt-1.0.0.tar.gz (2.9 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
    
      error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [21 lines of output]
      As of v1.0.0, `pip install dbt` is no longer supported.
      Instead, please use one of the following.
      
      **To use dbt with your specific database, platform, or query engine:**
      
          pip install dbt-<adapter>
      
          See full list: https://docs.getdbt.com/docs/available-adapters
      
      **For developers of integrations with dbt Core:**
      
          pip install dbt-core
      
          Be advised, dbt Cores python API is not yet stable or documented
          (https://docs.getdbt.com/docs/running-a-dbt-project/dbt-api)
      
      **For the previous behavior of `pip install dbt`:**
      
          pip install dbt-core dbt-postgres dbt-redshift dbt-snowflake dbt-bigquery
      
      [end of output]
    
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
    This is likely caused by a bug in dbt-ipy. Report this to its maintainers.

**Comment by jmriego** [comment]
Hi!

Yes, I can reproduce this. It was caused by now having to install dbt in a different way since v1. I'll update the repo.

On the meantime you can still install this by doing it this way:
```
pip install dbt-core
pip install dbt-postgres # or whatever adapter you need
pip install  --no-dependencies dbt-ipy
```

let me know if this fixes it for you

**Comment by MateTorok** [comment]
Thank you for your quick response! Installing this way worked!

**Comment by jmriego** [comment]
No worries! glad to hear that.
By the way, I have already pushed the changes to the repo so it's not necessary any more to do this workaround.
Hope this repo is useful to you!
